wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1634495751
    t:
      3:
      - 2
      4: 3.8.12
      5: 0.12.4
      8:
      - 5
