wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.4
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1634588432
    t:
      4: 3.8.12
      5: 0.12.4
      8:
      - 1
      - 5
augmentations:
  desc: null
  value:
    crop_size: 224
    rot_angle: 45
batch_size:
  desc: null
  value: 128
weight_decay:
  desc: null
  value: 0.01
